version: "3.8"

services:
  nginx:
    build:
      context: ./Back_end/Reverse_proxy
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - api_database
      - image_classification

  api_database:
    build:
      context: ./Back_end/api_database
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
    volumes:
      - ./Back_end/api_database:/app

  image_classification:
    build:
      context: ./Back_end/image_classification
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - ./Back_end/image_classification:/app
  frontend:
    build:
      context: ./Front_end
      dockerfile: Dockerfile  
    ports:
      - "3000:3000" 
    volumes:
      - ./Front_end:/usr/src/Front_end 
    depends_on:
      - api_database
      - image_classification 